"""created roles, users, service_requests and audit_logs tables

Revision ID: 89ff6f32c527
Revises: 
Create Date: 2025-09-07 02:16:35.423978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ff6f32c527'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('RoleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoleName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('Mobile', sa.String(length=20), nullable=True),
    sa.Column('Salt', sa.String(length=64), nullable=False),
    sa.Column('PasswordHash', sa.String(length=128), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('RoleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RoleID'], ['roles.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('audit_logs',
    sa.Column('LogID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Action', sa.String(length=200), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_table('service_requests',
    sa.Column('RequestID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ServiceType', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FeeAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('RequestID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_requests')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
